name: tennistrainer
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pytorch=2.*
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip
  - pip:
      - ultralytics
      - opencv-python-headless<5
      - bytetrack
      - pytest
      - black
      - ruff
